### ISSUE TITLE
多个项目能解析吗？

### ISSUE THREAD

**Issue by igaobingbing** [DreamNya/invoice-ofd2json#2]

**Comment by DreamNya** [comment]
支持多页发票，但不支持含销货清单的多页发票。

多张发票的话重复调用接口就行了。

**Comment by igaobingbing** [comment]
![image](https://github.com/DreamNya/invoice-ofd2json/assets/74999292/4d70abd2-1da9-405b-b24d-47f691965bba)
价税合计（大写）没出来

**Comment by DreamNya** [comment]
这个项目没有固定ID，每张发票基本都不一样，目前没有什么比较好的解决办法

https://github.com/DreamNya/invoice-ofd2json/blob/bd6d916e7ef824f3ef4379e40810942c9fa20f14/src/parser.js#L57

**Comment by igaobingbing** [comment]
手动把ID配置到源码可以吧?如果可以，添加一个类似push方法就行

**Comment by DreamNya** [comment]
因为我工作变动，这个库今年应该不会再更新了，你可以直接改库源码，也可以对返回的json做一层包装把UnknowID做个自定义映射

**Comment by igaobingbing** [comment]
数电客票和行程单不支持吧

**Comment by DreamNya** [comment]
只支持正规格式发票
